version: "3.9"

services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - PORT=5000

  mongo:
      image: mongo
      container_name: mongo
      restart: unless-stopped
      tty: true
      ports:
        - 27017:27017
      volumes:
        - ./datadb:/etc/mongo
      environment:
        - MONGO_INITDB_ROOT_USERNAME=root
        - MONGO_INITDB_ROOT_PASSWORD=1234
      networks:
        - app-network

volumes:
  data:
    driver: local
networks:
  app-network:
    driver: bridge
