version: '3.9'

services:
  mongo:
    image: mongo
    container_name: mongo
    restart: unless-stopped
    tty: true
    ports:
      - 27017:27017
    volumes:
      - ./datadb:/etc/mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=1234
    networks:
      - mongo-compose-network

volumes:
  datadb:
    driver: local
networks:
  mongo-compose-network:
    driver: bridge
